project_id = "oeweykyazadobobjncfg"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.notify-contact]
    verify_jwt = false
  [functions.notify-order-status]
    verify_jwt = false
  [functions.generate-invoice]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
